name: Deploy Portfolio
on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_PASSWORD }}" \
               -d '{"type":"push","repository":"Portfolio-Website", "payload":${{ github.event }}}' \
               ${{ secrets.DEPLOYMENT_ENDPOINT }}